apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deploy
  namespace: biday
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: hwijae/biday-eureka-server:3.1
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-service:8888"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:"
            - name: SERVER_PORT
              value: "8761"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"


---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: biday
spec:
  type: ClusterIP
  selector:
    app: eureka
  ports:
    - port: 8761
      targetPort: 8761  


