apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp-deploy
  namespace: biday
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftp
  template:
    metadata:
      labels:
        app: ftp
    spec:
      containers:
        - name: ftp
          image: hwijae/biday-ftp-service:3.1
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-server:8888"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "ftp-service"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "false"
            - name: EUREKA_INSTANCE_INSTANCE_ID
              value: "ftp-service:${server.port}"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          ports:
            - containerPort: 9102

---
apiVersion: v1
kind: Service
metadata:
  name: ftp-service
  namespace: biday
spec:
  type: ClusterIP
  selector:
    app: ftp
  ports:
    - port: 9102
      targetPort: 9102

