apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deploy
  namespace: biday
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: hwijae/biday-user-service:3.1
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-server:8888"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "user-service"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "false"
            - name: EUREKA_INSTANCE_INSTANCE_ID
              value: "user-service:${server.port}"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          ports:
            - containerPort: 9106
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: biday
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - port: 9106
      targetPort: 9106

