pipeline {
    agent any

    environment {
        DOCKER_HUB_URL = "${docker_hub_url}"
        GITHUB_URL = "${github_url}"
        DOCKER_HUB_CREDENTIAL = 'dockerhub'
        GIT_SSH_CREDENTIALS = 'github_ssh'
//         KUBECONFIG = "${env.WORKSPACE}/.ncloud/kubeconfig"
        KUBECONFIG = '/var/lib/jenkins/.ncloud/kubeconfig'
    }

    tools {
        jdk 'openjdk_17'
        gradle 'gradle_8.10'
    }

    stages {
        stage('Initialize') {
            steps {
                script {
                    modulePaths = [
                       "config-server": "/var/lib/jenkins/workspace/biday-spring-cloud/backend/server/config-server",
                       "eureka-server": "/var/lib/jenkins/workspace/biday-spring-cloud/backend/server/eureka-server",
                       "gateway-server": "/var/lib/jenkins/workspace/biday-spring-cloud/backend/server/gateway-server",
                       "admin-service": "/var/lib/jenkins/workspace/biday-spring-cloud/backend/service/admin-service",
                       "auction-service": "/var/lib/jenkins/workspace/biday-spring-cloud/backend/service/auction-service",
                       "ftp-service": "/var/lib/jenkins/workspace/biday-spring-cloud/backend/service/ftp-service",
                       "order-service": "/var/lib/jenkins/workspace/biday-spring-cloud/backend/service/order-service",
                       "product-service": "/var/lib/jenkins/workspace/biday-spring-cloud/backend/service/product-service",
                       "sms-service": "/var/lib/jenkins/workspace/biday-spring-cloud/backend/service/sms-service",
                       "user-service": "/var/lib/jenkins/workspace/biday-spring-cloud/backend/service/user-service"
                   ]
                }
            }
        }

        stage('Github ') {
            steps {
                script {
                    echo "Deinitializing and updating submodule..."
                    sh 'git submodule deinit -f backend/server/secret-server'
                    sh 'git submodule update --init --recursive'
                }

                checkout scmGit(
                    branches: [[name: '*/main']],
                    extensions: [
                        submodule(parentCredentials: true, recursiveSubmodules: true, reference: '', trackingSubmodules: true)
                    ],
                    userRemoteConfigs: [
                        [credentialsId: GIT_SSH_CREDENTIALS, url: GITHUB_URL]
                    ]
                )
            }
        }

        stage('Gradle Build') {
            steps {
                echo '=== build modules shell script start ==='
                dir('backend') {
                    script {
                        sh 'chmod +x gradlew'

                        def allModules = [
                            "server:config-server",
                            "server:eureka-server",
                            "server:gateway-server",
                            "service:admin-service",
                            "service:auction-service",
                            "service:ftp-service",
                            "service:order-service",
                            "service:product-service",
                            "service:sms-service",
                            "service:user-service"
                        ]

                        echo "Cleaning..."
                        sh './gradlew clean'

                        allModules.each { module ->
                            echo "Building for ${module}"
                            sh "./gradlew :${module}:bootJar"
                        }

//                     sh 'chmod +x buildModule.sh'
//                     sh './buildModule.sh'
                    }
                }
            }
        }

        stage('Docker Image Build') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_HUB_CREDENTIAL) {
                        modulePaths.each { module, path ->
                            echo "Building Docker image for ${module}"
                            sh """
                               docker build -t ${DOCKER_HUB_URL}/biday-${module}-personal:${BUILD_TAG} ${path}
                            """
                        }
                    }
                }
            }
        }

        stage('Docker Image Push') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_HUB_CREDENTIAL) {
                        modulePaths.each { module, path ->
                            echo "Pushing Docker image for ${module}"
                            sh """
                               docker push ${DOCKER_HUB_URL}/biday-${module}-personal:${BUILD_TAG}
                            """
                        }
                    }
                }
            }
        }

        // kuber
        stage('Kubernetes 배포') {
            steps {
                script {
                    echo "Kubernetes로 배포 중..."

                    // KUBECONFIG 파일의 존재 여부 확인
                    if (fileExists(KUBECONFIG)) {
                        echo "KUBECONFIG 파일이 존재합니다: ${KUBECONFIG}"

                        // kubectl을 사용하여 클러스터 상태 확인
                        sh 'kubectl cluster-info'

                        modulePaths.each { module, path ->
                            echo "Deploying ${module} to Kubernetes..."
                            sh """
                                kubectl set image deployment/${module} ${module}=${DOCKER_HUB_URL}/biday-${module}-personal:${BUILD_TAG} --namespace=my-namespace
                            """
                        }
                    } else {
                        error "KUBECONFIG 파일이 존재하지 않습니다: ${KUBECONFIG}"
                    }
                }
            }
        }
    }

    post{
        success{
            echo "========pipeline executed successfully ========"
            echo "Image 정리..."
            script {
                modulePaths.each { module, path ->
                    echo "Clean Docker image for ${module}"
                    sh """
                       docker rmi ${DOCKER_HUB_URL}/biday-${module}-personal:${BUILD_TAG}
                    """
                }
            }
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}